---
# ansible_role_workstation/tasks/rhel8.yml
# Author: MTO 
# Description: Task for installing default GUI and programs on RedHat 8 or Centos 8.
# Requirement EPEL repo must be installed
#
#- name: Upgrade all packages (RedHat 8)
#  yum:
#    name: '*'
#    state: latest
  
- name: Limit the number of kernels (RedHat 8)
  lineinfile:
    path: /etc/yum.conf
    regexp: '^installonly_limit'
    line: installonly_limit=2
    state: present
  

  

