---
# ansible_role_workstation/tasks/fedora.yml
# Author: MTO 
# Description: Task for installing default GUI and programs on Fedora
#
- name: Upgrade all packages (Fedora)
  dnf:
    name: '*'
    state: latest
   
- name: Install Gnome Minimal (Fedora)
  dnf:
    name:
      - gnome-shell
      - gnome-terminal
      - dejavu-sans-mono-fonts
      - bash-completion
    state: present    
   
- name: Get default runlevel (Fedora)
  command: systemctl get-default
  register: runlevel
   
- name: Set graphical runlevel (Fedora)
  command: systemctl set-default graphical.target
  when: runlevel.stdout != "graphical.target"
  
- name: Is graphical currently active (Fedora)
  command: systemctl is-active graphical.target
  ignore_errors: true
  register: graphical
  
- name: Switch to graphical runlevel (Fedora)
  command: systemctl isolate graphical.target
  when: graphical.stdout != "active"
  ignore_errors: true   
  
- name: Install agent software (Fedora)
  dnf:
    name:
      - spice-vdagent
      - spice-server
      - spice-glib
      - spice-gtk3 
    state: present 
   
- name: Install default software (Fedora)
  dnf:
    name:
      - gnome-terminal
      - gnome-tweak-tool
      - bash-completion
      - net-tools
      - bind-utils
      - dnf-utils
      - sos
      - git
      - vim
      - traceroute
      - unzip
      - mlocate
      - eog
      - tree
      - evince
      - screen
    state: present     
    
- name: Install fonts (Fedora)
  dnf:
    name:
      - fontconfig 
      - dejavu-sans-fonts 
      - dejavu-sans-mono-fonts 
      - dejavu-serif-fonts 
      - liberation-mono-fonts 
      - liberation-sans-fonts 
      - liberation-serif-fonts
      #- adobe-source-han-sans-cn-fonts 
      #- adobe-source-han-serif-cn-fonts 
      #- google-noto-sans-thai-fonts 
      #- google-noto-serif-thai-fonts 
      #- un-core-batang-fonts
    state: present     
     
- name: Disable Wayland (Fedora)
  lineinfile:
    path: /etc/gdm/custom.conf
    regexp: '^#WaylandEnable='
    line: WaylandEnable=false
    state: present
   
- name: Limit the number of kernels (Fedora)
  lineinfile:
    path: /etc/dnf.conf
    regexp: '^installonly_limit'
    line: installonly_limit=1
    state: present
  
- name: Remove old kernels from the OS keeping only the most recent (Fedora)
  command: dnf remove $(dnf repoquery --installonly --latest-limit=-1 -q) -y

- name: Unconditionally reboot (Fedora)
  reboot: