---
# ansible_role_workstation/tasks/main.yml
# Author: MTO 
# Description: Main task for installing default GUI and programs on Fedora, RedHat 8.
#
- name: MAIN - Display system, os, version and release 
  debug: msg="SYSTEM {{ inventory_hostname }} | OS {{ ansible_distribution }} | VERSION {{ ansible_distribution_version }} | RELEASE {{ ansible_distribution_release }}"

- include_tasks: "{{ ansible_os_family | lower }}{{ ansible_distribution_version }}_system.yml"
- include_tasks: "{{ ansible_os_family | lower }}{{ ansible_distribution_version }}_software.yml"
- include_tasks: "{{ ansible_os_family | lower }}{{ ansible_distribution_version }}_fonts.yml"
- include_tasks: "{{ ansible_os_family | lower }}{{ ansible_distribution_version }}_gnome.yml"
- include_tasks: "{{ ansible_os_family | lower }}{{ ansible_distribution_version }}_user.yml"
- name: MAIN - Unconditionally reboot
  reboot:

  