---
# ansible_role_workstation/tasks/redhat8.0_user.yml
# Author: MTO 
# Description: Task for setting user on RedHat 8 or Centos 8.
# 
- name: USER - Add the user "{{ user }}"
  user:
    name: "{{ user_username }}"
    password: "{{ user_password }}"
    comment: "{{ user_geco }}"
    group: "{{ user_username }}, wheel"
    state: present
    shell: /bin/bash                             # Defaults to /bin/bash
    system: no                                   # Defaults to no
    createhome: yes                              # Defaults to yes
    home: "/home/{{ user_username }}"  # Defaults to /home/<username>

#- name: USER - Create custom user locations if it doesn't exist
#  file:
#    path: "{{ item }}"
#    state: directory
#    mode: 0755
#    owner: "{{ configure_user_username }}" 
#    group: "{{ configure_user_username }}"
#  loop : "{{ configure_user_locations }}"
