---
# ansible_role_workstation/tasks/redhat_user.yml
# Author: MTO 
# Description: Task for configuring user settings on RedHat 8.
# 
- name: USER - Create account
  user:
    name: "{{ usr.uname }}"
    password: "{{ usr.upass | password_hash('sha512') }}"
    groups: wheel
    append: yes
    shell: /bin/bash
    update_password: on_create
    state: present
  no_log: true

- name: USER - Set Private key for account
  authorized_key:
    user: "{{ usr.uname }}"
    key: "{{ usr.ukey}}"
    exclusive: yes
  no_log: true  

- name: USER - Gnome configure with dconf module (RedHat 8)
  dconf:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
  become: True
  become_user: "{{ usr.uname }}"
  loop: "{{ workstation_gnome_settings }}"

#- name: USER - VSCode install extensions
#  become: yes
#  become_user: "{{ usr.uname }}"
#  visual_studio_code_install_extension:
#    executable: '{{ visual_studio_code_exe }}'
#    name: '{{ item.1 }}'
#  with_subelements:
#    - workstation_software_vsc_extensions
#- skip_missing: yes

# - name: USER - Set ThunderBird Data

# - name USER - Set FireFox Data