---
# ansible_role_workstation/tasks/redhat8.0_software.yml
# Author: MTO 
# Description: Task for installing software on RedHat 8.
# Requirements: EPEL Repository
#
- name: SOFTWARE - Install agent software (RedHat 8)
  yum:
    name:
      - spice-vdagent
      - spice-server
      - spice-glib
      - spice-gtk3 
    state: present 

- name: SOFTWARE - Install default software (RedHat 8)
  yum:
    name:
      - gnome-terminal
      - bash-completion
      - net-tools
      - bind-utils
      - dnf-utils
      - dconf-editor
      - python3-psutil
      - sos
      - git
      - vim
      - traceroute
      - unzip
      - mlocate
      - eog
      - tree
      - evince
      - screen
    state: present   


    