# ansible_role_workstation/tasks/redhat8.0_gnome.yml
# Author: MTO 
# Description: Task for installing minimal Gnome UI on RedHat 8.
# Requirements: redhat8.0_software.yml has to run first 
#
- name: GNOME - Install Gnome Minimal (RedHat 8)
  yum:
    name:
      - gnome-shell
    state: present    
  
- name: GNOME - Get default runlevel (RedHat 8)
  command: systemctl get-default
  register: runlevel
  
- name: GNOME - Set graphical runlevel (RedHat 8)
  command: systemctl set-default graphical.target
  when: runlevel.stdout != "graphical.target"
  
- name: GNOME - Is graphical currently active (RedHat 8)
  command: systemctl is-active graphical.target
  ignore_errors: true
  register: graphical
  
- name: GNOME - Switch to graphical runlevel (RedHat 8)
  command: systemctl isolate graphical.target
  when: graphical.stdout != "active"
  ignore_errors: true   
      
- name: GNOME - Disable Wayland (RedHat 8)
  lineinfile:
    path: /etc/gdm/custom.conf
    regexp: '^#WaylandEnable='
    line: WaylandEnable=false
    state: present

- name: GNOME - GDM disable user list (1) - Create dir /etc/dconf/db/gdm.d
  file:
    path: /etc/dconf/db/gdm.d
    state: directory
    owner: root
    group: root
    mode: '0755'
  
- name: GNOME - GDM disable user list (2) - Template a file to /etc/dconf/db/gdm.d/01-settings
  template:
    src: etc/dconf/db/gdm.d/01-settings.j2
    dest: /etc/dconf/db/gdm.d/01-settings
    owner: root
    group: root
    mode: '0644'

- name: GNOME - GDM disable user list (3) - Template a file to /etc/dconf/profile/gdm
  template:
    src: etc/dconf/profile/gdm.j2
    dest: /etc/dconf/profile/gdm
    owner: root
    group: root
    mode: '0644'

- name:  GNOME - GDM disable user list (4) - Update DCONF 
  command: dconf update