---

- name: Display from rhel8-setup
  debug: msg="Setup system {{ inventory_hostname }}"

- name: Upgrade all packages
  yum:
    name: '*'
    state: latest

- name: Install Gnome Minimal
  yum:
    name:
      - "@base-x" 
      - gnome-shell
      - gnome-terminal
      - dejavu-sans-mono-fonts
      - bash-completion
    state: present    

- name: Get default runlevel
  command: systemctl get-default
  register: runlevel

- name: Set graphical runlevel
  command: systemctl set-default graphical.target
  when: runlevel.stdout != "graphical.target"

- name: Is graphical currently active
  command: systemctl is-active graphical.target
  register: graphical
  ignore_errors: true

- name: Switch to graphical runlevel
  command: systemctl isolate graphical.target
  when: graphical.stdout != "active"
  ignore_errors: true   

- name: Install default software
  yum:
    name:
      - spice-vdagent
      - spice-server
      - spice-glib
      - spice-gtk3
      - gnome-terminal
      - gnome-tweak-tool
      - bash-completion
      - firefox
      - thunderbird
      - net-tools
      - bind-utils
      - git
      - vim
      - traceroute
      - unzip
      - mlocate
      - eog
      - tree
    state: present     

- name: Install fonts
  yum:
    name:
      - fontconfig 
      - dejavu-sans-fonts 
      - dejavu-sans-mono-fonts 
      - dejavu-serif-fonts 
      - liberation-mono-fonts 
      - liberation-sans-fonts 
      - liberation-serif-fonts
      #- adobe-source-han-sans-cn-fonts 
      #- adobe-source-han-serif-cn-fonts 
      #- google-noto-sans-thai-fonts 
      #- google-noto-serif-thai-fonts 
      #- un-core-batang-fonts
    state: present     
